---
title: "SARS-CoV-2 & Other Diseases"
date: "`r Sys.Date()`"
output: 
  rmdformats::downcute:
    self_contained: true
    highlight: kate
    toc_depth: 3
    default_style: dark
    code_folding: hide
    code_download: true
    highlight_downlit: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

# Paquetes
```{r}
library(tidyverse)
library(innovar)
```

# Data Wrangling

```{r}
#Reading COVID-19 and FFI data

covid_others <- read.csv("01_data/processed/FFI Peru_seropositivity_NEG_cutoff.csv") %>% 
  filter(Sample != "MISTAKE") %>%
  select(2,19:34) %>% 
  mutate(Sample = str_extract(Sample, "\\d+"),
         Sample = case_when(
           Sample == "010204904" ~ "10204904",
           TRUE ~ Sample
         )) %>% 
  mutate(
    ffi_is_code = paste0(0,Sample)
  ) %>% 
  relocate(ffi_is_code,
           .after = Sample) %>% 
  select(-Sample)

ffi <- readRDS("01_data/processed/ffi_total.rds")

ffi_total <- covid_others %>% 
  left_join(
    ffi, by = "ffi_is_code"
  )
  

# Exporting data for Martina
# ffi_total <- ffi_total %>% 
#   unite("ffi_h_code", ffi_is_cod_proy:ffi_is_cod_household, sep = "") %>% 
#   select(ffi_h_code, ffi_is_code, ffi_is_district, ffi_is_community, 
#          SEA_pos, age_cat, gender, economic_activities, education_level,
#          ffi_is_trip_month, ffi_is_place_shower,
#          ffi_is_age_fixed) 

# ffi_households <- readRDS("01_data/processed/ffi_household.rds") %>% 
#   select(ffi_h_code ,ffi_gps_lat, ffi_gps_long)
# 
# 
# ffi_locations <- ffi_total %>% 
#   left_join(ffi_households)

#write_csv(ffi_locations, "01_data/processed/ffi_locations.csv")
```

# General Plot

```{r}
ffi_total <- ffi_total %>% 
  group_by(ffi_is_district) %>% 
  mutate(
    distance_to_rh_hf_sampl = as.numeric(cut_number(distance_to_rh_hf_sampl_num, 3)),
    distance_to_rh_hf_sampl = factor(distance_to_rh_hf_sampl, 
                                     labels = c("Proximate", "Moderate",
                                                "Distant"))
  ) %>% 
  ungroup()
```


```{r}
ffi_sero <- ffi_total %>% 
  select(ffi_is_code, ffi_is_district,
         age_cat, distance_to_rh_hf_sampl, 
         X229.E.NP_pos:MERSP.NP_pos,
         OC43.NP_pos, SARS.NP.WT_pos,
         SEA_pos:Zika.NS1_pos) %>% 
  drop_na() %>% 
  pivot_longer(
    cols = c(X229.E.NP_pos:Zika.NS1_pos),
    names_to = "Disease",
    values_to = "Cases"
  ) %>% 
  group_by(ffi_is_district, age_cat, 
           distance_to_rh_hf_sampl,
           Disease) %>% 
  summarise(result_exposure = mean(Cases))

ffi_sero <- ffi_sero %>% 
  mutate(
    Disease = fct_recode(
      Disease,
      "Chikungunya" = "Chik.E1_pos",
      "Dengue - Type 1" = "Dengue.NS1.1_pos",
      "Dengue - Type 2" = "Dengue.NS1.2_pos",
      "Dengue - Type 3" = "Dengue.NS1.3_pos",
      "Dengue - Type 4" = "Dengue.NS1.4_pos",
      "Influenza" = "H3N2_pos",
      "Common Cold 1" = "HKV1.NP_pos",
      "MERS" = "MERSP.NP_pos",
      "Common Cold 2" = "OC43.NP_pos",
      "COVID-19" = "SARS.NP.WT_pos", 
      "Schistosomiasis" = "SEA_pos",
      "Tetanus toxoid" = "Tet.Tox_pos",
      "Human coronavirus - 229E" = "X229.E.NP_pos",
      "Zika" = "Zika.NS1_pos"
    )
  ) %>% 
  ungroup()
```


```{r}
plot_ffi_sero1 <-
  ffi_sero %>% 
  filter(
    Disease %in% c("Dengue - Type 1",
                   "Dengue - Type 2",
                   "Dengue - Type 3",
                   "Dengue - Type 4",
                   "Chikungunya",
                   "Zika")
  ) %>% 
  ggplot(
    aes(
      x = age_cat,
      y = result_exposure,
      color = Disease,
      group = Disease
    )
  ) +
  geom_point() +
  geom_line() +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  ) +
  labs(
    x = "Age",
    y = "Seropositivity",
    title = str_wrap("Seropositivity  by District and distance category of the communities to Loreto Regional Hospital and Health Facilities on a Sampling Basis", 80)
  ) +
  guides(
    color = guide_legend("Disease")
  ) +
  viridis::scale_color_viridis(discrete = TRUE,
                               option = "D",
                               end = 0.82) +
  #scale_color_brewer(palette = "Set3") +
  #innovar::scale_color_innova("npr") +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    )
  )
```

```{r}
ggsave(
  "plot_ffi_sero1.png",
  plot = plot_ffi_sero1,
  width = 10,
  height = 6,
  dpi = 400
)
```



```{r}
plot_ffi_sero2 <-
  ffi_sero %>% 
  filter(
    !Disease %in% c("Dengue - Type 1",
                   "Dengue - Type 2",
                   "Dengue - Type 3",
                   "Dengue - Type 4",
                   "Chikungunya",
                   "Zika")
  ) %>% 
  ggplot(
    aes(
      x = age_cat,
      y = result_exposure,
      color = Disease,
      group = Disease
    )
  ) +
  geom_point() +
  geom_line() +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  ) +
  labs(
    x = "Age",
    y = "Seropositivity",
    title = str_wrap("Seropositivity  by District and distance category of the communities to Loreto Regional Hospital and Health Facilities on a Sampling Basis", 80)
  ) +
  guides(
    color = guide_legend("Disease")
  ) +
  viridis::scale_color_viridis(discrete = TRUE,
                               option = "D",
                               end = 0.82) +
  #scale_color_brewer(palette = "Set3") +
  #innovar::scale_color_innova("npr") +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    )
  )
plot_ffi_sero2
```

```{r}
ggsave(
  "plot_ffi_sero2.png",
  plot = plot_ffi_sero2,
  width = 10,
  height = 6,
  dpi = 400
)
```




# SARS-CoV-2 Seropositivity

```{r}

sero_covid <- ffi_total %>% 
  select(ffi_is_code, ffi_is_district, age_cat,distance_to_rh_hf_sampl, SARS.NP.WT_pos) %>% 
  drop_na() %>% 
  mutate(
    exposure = case_when(
       SARS.NP.WT_pos == 1 ~"Seropositive",
       TRUE ~ "Seronegative"
    )
  ) %>% 
  group_by(ffi_is_district, age_cat, distance_to_rh_hf_sampl) %>% 
  count(exposure) %>% 
  mutate(
    result_exposure = n/sum(n)
  ) %>% 
  select(-n) %>% 
  ungroup() %>% 
  mutate(
    distance_to_rh_hf_sampl = fct_relevel(distance_to_rh_hf_sampl, 
                                      "Proximate", "Moderate",
                                      "Distant", "Extra Distant")
  ) %>% 
  ggplot(
    aes(
      x = age_cat,
      y = result_exposure,
      color = exposure,
      group = exposure
    )
  ) +
  geom_point() +
  geom_line() +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  )+
  labs(
    x = "Age",
    y = "Seropositivity",
    title = str_wrap("SARS-CoV-2 Seropositivity  by District and distance category of the communities to Loreto Regional Hospital and Health Facilities on a Sampling Basis", 80)
  ) +
  guides(
    color = guide_legend("SARS-CoV-2")
  ) +
  innovar::scale_color_innova("npr") +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    )
  )

sero_covid 

```



# Schistosomiasis Seropositivity

```{r}

sero_sea <- ffi_total %>% 
  select(ffi_is_code, ffi_is_district, age_cat,distance_to_rh_hf_sampl, SEA_pos) %>% 
  drop_na() %>% 
  mutate(
    exposure = case_when(
       SEA_pos == 1 ~"Seropositive",
       TRUE ~ "Seronegative"
    )
  ) %>% 
  group_by(ffi_is_district, age_cat, distance_to_rh_hf_sampl) %>% 
  count(exposure) %>% 
  mutate(
    result_exposure = n/sum(n)
  ) %>% 
  select(-n) %>% 
  ungroup() %>% 
  mutate(
    distance_to_rh_hf_sampl = fct_relevel(distance_to_rh_hf_sampl, 
                                      "Proximate", "Moderate",
                                      "Distant", "Extra Distant")
  ) %>% 
  ggplot(
    aes(
      x = age_cat,
      y = result_exposure,
      color = exposure,
      group = exposure
    )
  ) +
  geom_point() +
  geom_line() +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  )+
  labs(
    x = "Age",
    y = "Seropositivity",
    title = str_wrap("Schistosomiasis Seropositivity  by District and distance category of the communities to Loreto Regional Hospital and Health Facilities on a Sampling Basis", 80)
  ) +
  guides(
    color = guide_legend("Schistosomiasis")
  ) +
  innovar::scale_color_innova("npr") +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    )
  )

sero_sea 

```



# ZIKA Seropositivity

```{r}

a <- ffi_total %>% 
  filter(ffi_is_district == "Indiana") %>% 
  group_by(distance_to_rh_hf_sampl) %>% 
  count(ffi_is_community)


sero_zika <- ffi_total %>% 
  select(ffi_is_code, ffi_is_district, age_cat,distance_to_rh_hf_sampl, Zika.NS1_pos) %>% 
  drop_na() %>% 
  mutate(
    exposure = case_when(
       Zika.NS1_pos == 1 ~"Seropositive",
       TRUE ~ "Seronegative"
    )
  ) %>% 
  group_by(ffi_is_district, age_cat, distance_to_rh_hf_sampl) %>% 
  count(exposure) %>% 
  mutate(
    result_exposure = n/sum(n)
  ) %>% 
  select(-n) %>% 
  ungroup() %>% 
  mutate(
    distance_to_rh_hf_sampl = fct_relevel(distance_to_rh_hf_sampl, 
                                      "Proximate", "Moderate",
                                      "Distant", "Extra Distant")
  ) %>% 
  ggplot(
    aes(
      x = age_cat,
      y = result_exposure,
      color = exposure,
      group = exposure
    )
  ) +
  geom_point() +
  geom_line() +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  )+
  labs(
    x = "Age",
    y = "Seropositivity",
    title = str_wrap("ZIKA Seropositivity  by District and distance category of the communities to Loreto Regional Hospital and Health Facilities on a Sampling Basis", 80)
  ) +
  guides(
    color = guide_legend("ZIKA")
  ) +
  innovar::scale_color_innova("npr") +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    )
  )

sero_zika

```





```{r}
# Reading river distance data

# river <- read.csv("01_data/processed/ffi_distance_to_rivers.csv") %>%
#   mutate(
#     ffi_h_code = as.character(ffi_h_code),
#     ffi_h_code = paste0(0,ffi_h_code)
#   )
# 
# # Calculating seropositivity by household
# 
# sero_schisto <- ffi_total %>%
#   group_by(ffi_h_code) %>%
#   summarise(numerador = sum(SEA_pos),
#          denominador = n(),
#          schisto_sero = round((numerador/denominador)*100, 2)
#          ) %>%
#   ungroup() %>%
#   mutate(
#     sample_ponderation = denominador/mean(denominador),
#     seropositivity_ponderated = schisto_sero*sample_ponderation
#   )
# 
# schisto_total <- river %>%
#   inner_join(sero_schisto, by = "ffi_h_code")
# 
# #Seropositivity in age-school children
# 
# sero_age_school <- ffi_total %>%
#   mutate(
#     age_school = case_when(
#       ffi_is_age_fixed < 1 ~ "no_school_aged",
#       ffi_is_age_fixed >= 1 & ffi_is_age_fixed < 5  ~ "pre_school_aged",
#       ffi_is_age_fixed >= 5 &  ffi_is_age_fixed < 15 ~ "school_aged",
#       TRUE ~ "adults"
#     ),
#     sero_sea_cat = case_when(
#       SEA_pos == 1 ~ "seropositive",
#       TRUE ~ "seronegative"
#     )
#   ) %>%
#   filter(
#     age_school %in% c("pre_school_aged", "school_aged")
#   ) %>%
#   group_by(age_school, sero_sea_cat) %>%
#   count() %>%
#   ungroup() %>%
#   group_by(age_school) %>% 
#   mutate(
#     prop = n/sum(n)*100
#   )
# 
# 
# 
# # Ploting seropositivity
# 
# ## Ploting overall
# plot_total <- schisto_total %>%
#   group_by(ffi_h_code) %>%
#   filter(distance_km == min(distance_km)) %>%
#   ggplot(
#     aes(x = distance_km)
#     ) +
#   geom_histogram() +
#   facet_wrap(vars(name))
# 
# plot_total
# 
# ## Ploting positives
# 
# plot_posi <- schisto_total %>%
#   group_by(ffi_h_code) %>%
#   filter(distance_km == min(distance_km)) %>%
#   filter(seropositivity_ponderated>0) %>%
#   ggplot(
#     aes(x = distance_km)
#     ) +
#   geom_boxplot() +
#   facet_wrap(vars(name))
# 
# plot_posi
# 
# ## Plot negatives
# 
# plot_nega <- schisto_total %>%
#   group_by(ffi_h_code) %>%
#   filter(distance_km == min(distance_km)) %>%
#   filter(seropositivity_ponderated==0) %>%
#   ggplot(
#     aes(x = distance_km)
#     ) +
#   geom_boxplot() +
#   facet_wrap(vars(name))
# 
# plot_nega
# 
# 
# ggpubr::ggarrange(plot_total, plot_posi, plot_nega,
#                   ncol = 2, nrow = 2,
#                   hjust = 1)
# 
# 
# # Focused on + cases
# 
# plot_sero_cat <- schisto_total %>%
#   mutate(
#     quartile = ntile(seropositivity_ponderated, 4),
#     sero_cat = case_when(
#       quartile < 5 ~ ""
#     )
#   ) %>%
#   filter(
# 
#   )
# 
# 
# #Analisis de correlación
# 
# min_distance_total <- schisto_total %>%
#   group_by(ffi_h_code) %>%
#   filter(distance_km == min(distance_km)) %>%
#   ggplot(aes(x= distance_km)) +
#   geom_boxplot()
# 
# 
# min_distance_pos <- schisto_total %>%
#   filter(seropositivity_ponderated > 0) %>%
#   group_by(ffi_h_code) %>%
#   filter(distance_km == min(distance_km)) %>%
#   ggplot(aes(x= distance_km)) +
#   geom_histogram()
# 
# ggpubr::ggarrange(min_distance_total, min_distance_pos, ncol = 2, nrow = 1)
```


```{r}
#proportions
# library(gtsummary)
# 
# table_1 <- schisto_total %>%
#   group_by(ffi_h_code) %>%
#   filter(distance_km == min(distance_km)) %>%
#   mutate(
#     SEA_pos = case_when(
#       SEA_pos == "0" ~ "Seronegative",
#       TRUE ~ "Seropositive"
#     )
#   ) %>%
#   ungroup() %>%
#   select(
#     gender, ffi_is_district, age_cat,
#     education_level, economic_activities,
#     ffi_is_trip_month, ffi_is_place_shower,SEA_pos,
#     ffi_is_age_fixed
#   ) %>%
#   tbl_summary(
#     by = "SEA_pos"
#   )
# 
# table_1
# 
# table_1 %>%
#   gtsummary::as_flex_table() %>%
#   flextable::save_as_docx(path = "./02_output/reports/table1_schisto.docx")
```


# Aditional plots

## Boxplot



```{r}
ffi_sero_gender <- ffi_total %>% 
  select(ffi_is_code, ffi_is_district,
         gender, distance_to_rh_hf_sampl, 
         X229.E.NP_pos:MERSP.NP_pos,
         OC43.NP_pos, SARS.NP.WT_pos,
         SEA_pos:Zika.NS1_pos) %>% 
  drop_na() %>% 
  pivot_longer(
    cols = c(X229.E.NP_pos:Zika.NS1_pos),
    names_to = "Disease",
    values_to = "Cases"
  ) %>% 
  group_by(ffi_is_district, gender, 
           distance_to_rh_hf_sampl,
           Disease) %>% 
  summarise(result_exposure = mean(Cases)) %>% 
  mutate(
    Disease = fct_recode(
      Disease,
      "Chikungunya" = "Chik.E1_pos",
      "Dengue - Type 1" = "Dengue.NS1.1_pos",
      "Dengue - Type 2" = "Dengue.NS1.2_pos",
      "Dengue - Type 3" = "Dengue.NS1.3_pos",
      "Dengue - Type 4" = "Dengue.NS1.4_pos",
      "Influenza" = "H3N2_pos",
      "Common Cold 1" = "HKV1.NP_pos",
      "MERS" = "MERSP.NP_pos",
      "Common Cold 2" = "OC43.NP_pos",
      "COVID-19" = "SARS.NP.WT_pos", 
      "Schistosomiasis" = "SEA_pos",
      "Tetanus toxoid" = "Tet.Tox_pos",
      "Human coronavirus - 229E" = "X229.E.NP_pos",
      "Zika" = "Zika.NS1_pos"
    )
  )
```

```{r}
bar_plot_sero_gender <- ffi_sero_gender %>% 
  mutate(
    Disease = fct_reorder(Disease, result_exposure),
    gender = fct_reorder(gender, result_exposure, .desc = TRUE)
  ) %>% 
  ggplot(
    aes(
      x = result_exposure,
      y = Disease,
      fill = gender
    )
  ) +
  geom_col(position ="dodge") +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_x_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  ) +
  guides(
    fill = guide_legend("Gender",
                        reverse = TRUE)
  ) +
  innovar::scale_fill_innova("npr") + #"dark_green"
  labs(
    x = "Seropositivity",
    y = NULL,
    title = NULL
  ) +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    )
  )

bar_plot_sero_gender
```


```{r}
ggsave(
  "bar_plot_sero_gender.png",
  plot = bar_plot_sero_gender,
  width = 9,
  height = 8,
  dpi = 400
)
```


```{r}
plot_ffi_sero_gender <- ffi_sero_gender %>% 
  ggplot(
    aes(
      x = Disease,
      y = result_exposure,
      color = gender,
      group = gender
    )
  ) +
  geom_point() +
  geom_line() +
  facet_grid(
    vars(distance_to_rh_hf_sampl),
    vars(ffi_is_district)    
  ) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  ) +
  labs(
    x = "Disease",
    y = "Seropositivity",
    title = str_wrap("Seropositivity  by District and distance category of the communities to Loreto Regional Hospital and Health Facilities on a Sampling Basis", 80)
  ) +
  guides(
    color = guide_legend("Sex")
  ) +
  innovar::scale_color_innova("npr") +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    ),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

plot_ffi_sero_gender
```

```{r}
ggsave(
  "plot_ffi_sero_gender.png",
  plot = plot_ffi_sero_gender,
  width = 10,
  height = 6,
  dpi = 400
)
```



```{r}
grouped_ggbetweenstats(
  data             = ffi_sero_gender,
  x                = gender,
  y                = result_exposure,
  grouping.var     = Disease,
  # outlier.tagging  = TRUE,
  # outlier.label    = title,
  # outlier.coef     = 2,
  # ggsignif.args    = list(textsize = 4, tip_length = 0.01),
  # p.adjust.method  = "bonferroni",
  # palette          = "default_jama",
  # package          = "ggsci",
  # plotgrid.args    = list(nrow = 1),
  # annotation.args  = list(title = "Differences in movie length by mpaa ratings for different genres")
)
```



```{r}
boxplot_sero_gender <- ffi_sero_gender %>% 
  mutate(
    Disease = fct_reorder(Disease, result_exposure, .desc = TRUE)
  ) %>% 
  ggplot(
    aes(
      y = result_exposure,
      x = Disease,
      fill = gender
    )
  ) +
  geom_boxplot() +
  facet_wrap(vars(ffi_is_district),
             nrow = 2) +
  scale_y_continuous(
    labels = scales::percent_format(),
    #limits = c(0, 0.50)
  ) +
  guides(
    fill = guide_legend("Gender",
                        reverse = TRUE)
  ) +
  innovar::scale_fill_innova("npr") + #"dark_green"
  labs(
    x = "Seropositivity",
    y = NULL,
    title = NULL
  ) +
  theme_bw() +
  theme(
    plot.title = element_text(
      size = 14,
      hjust = 0.5,
      face = "bold"
    ),
    strip.text = element_text(
      size = 12,
      face = "bold"
    ),
    legend.title = element_text(
      size = 12,
      face = "bold"
    ),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )

boxplot_sero_gender
```


```{r}
ggsave(
  "boxplot_sero_gender.png",
  plot = boxplot_sero_gender,
  width = 8,
  height = 8,
  dpi = 400
)
```


## Sankey Plots


```{r}
library(ggsankey)
```

```{r}
ffi_sankey_format <- ffi_total %>% 
  mutate(
    Dengue = case_when(
      Dengue.NS1.1_pos == 1 | 
        Dengue.NS1.2_pos == 1 |
        Dengue.NS1.3_pos == 1 | 
        Dengue.NS1.4_pos == 1 ~ 1,
      .default = 0
    ),
    across(
      c(SARS.NP.WT_pos, Dengue,
        Zika.NS1_pos),
      ~ case_match(
        .,
        1 ~ "Positive",
        .default = "Negative"
      )
    )
  ) %>% 
  select(gender, ffi_is_trip_month, 
         SARS.NP.WT_pos, 
         Dengue,
         any_pv_pf_exposure,
         Zika.NS1_pos) %>% 
  drop_na()
```

### Sankey Covid

```{r}
relabels_sankey_covid <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, SARS.NP.WT_pos) %>% 
  count(x, node) %>% 
  group_by(x) %>% 
  mutate(
    percentage = scales::percent(
      n / sum(n),
      accuracy = 0.1
    ),
    node2 = paste0(
      node,
      paste0("\n(", percentage, ")")
    )
  ) %>% 
  ungroup() %>% 
  select(-c(n, percentage))
  
sankey_covid <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, SARS.NP.WT_pos) %>% 
  left_join(
    relabels_sankey_covid,
    by = join_by(x, node)
  ) %>% 
  left_join(
    relabels_sankey_covid,
    by = join_by(next_x == x, 
                 next_node == node)
  ) %>% 
  mutate(node = node2.x,
         next_node = node2.y) %>% 
  select(-c(node2.x, node2.y)) %>% 
  ggplot(aes(
    x = x,
    next_x = next_x,
    node = node,
    next_node = next_node,
    fill = factor(node),
    label = node
  )) +
  geom_sankey(
    flow.alpha = .8,
    node.color = "gray30"
  ) +
  geom_sankey_label(size = 4,
                    color = "white",
                    fill = "gray30") +
  scale_x_discrete(
    labels = c("Sex", 
               "Have you been on a trip in the last month?",
               "COVID - 19")
  ) +
  labs(
    x = NULL,
    title = NULL
  ) +
  theme_sankey(base_size = 18) +
  innovar::scale_fill_innova("npr") +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = .5),
    plot.margin = margin(5, 0, 5, 0)
  )

sankey_covid
```


```{r eval=FALSE}
ggsave("./sankey_seropositive_covid.png",
       sankey_covid,
       height = 7,
       width = 12,
       dpi = 300)
```



### Sankey Dengue

```{r}
relabels_sankey_dengue <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, Dengue) %>% 
  count(x, node) %>% 
  group_by(x) %>% 
  mutate(
    percentage = scales::percent(
      n / sum(n),
      accuracy = 0.1
    ),
    node2 = paste0(
      node,
      paste0("\n(", percentage, ")")
    )
  ) %>% 
  ungroup() %>% 
  select(-c(n, percentage))
  
sankey_dengue <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, Dengue) %>% 
  left_join(
    relabels_sankey_dengue,
    by = join_by(x, node)
  ) %>% 
  left_join(
    relabels_sankey_dengue,
    by = join_by(next_x == x, 
                 next_node == node)
  ) %>% 
  mutate(node = node2.x,
         next_node = node2.y) %>% 
  select(-c(node2.x, node2.y)) %>% 
  ggplot(aes(
    x = x,
    next_x = next_x,
    node = node,
    next_node = next_node,
    fill = factor(node),
    label = node
  )) +
  geom_sankey(
    flow.alpha = .8,
    node.color = "gray30"
  ) +
  geom_sankey_label(size = 4,
                    color = "white",
                    fill = "gray30") +
  scale_x_discrete(
    labels = c("Sex", 
               "Have you been on a trip in the last month?",
               "Dengue")
  ) +
  labs(
    x = NULL,
    title = NULL
  ) +
  theme_sankey(base_size = 18) +
  innovar::scale_fill_innova("npr") +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = .5),
    plot.margin = margin(5, 0, 5, 0)
  )

sankey_dengue
```


```{r eval=FALSE}
ggsave("./sankey_seropositive_dengue.png",
       sankey_dengue,
       height = 7,
       width = 12,
       dpi = 300)
```


### Sankey Zika

```{r}
relabels_sankey_zika <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, Zika.NS1_pos) %>% 
  count(x, node) %>% 
  group_by(x) %>% 
  mutate(
    percentage = scales::percent(
      n / sum(n),
      accuracy = 0.1
    ),
    node2 = paste0(
      node,
      paste0("\n(", percentage, ")")
    )
  ) %>% 
  ungroup() %>% 
  select(-c(n, percentage))
  
sankey_zika <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, Zika.NS1_pos) %>% 
  left_join(
    relabels_sankey_zika,
    by = join_by(x, node)
  ) %>% 
  left_join(
    relabels_sankey_zika,
    by = join_by(next_x == x, 
                 next_node == node)
  ) %>% 
  mutate(node = node2.x,
         next_node = node2.y) %>% 
  select(-c(node2.x, node2.y)) %>% 
  ggplot(aes(
    x = x,
    next_x = next_x,
    node = node,
    next_node = next_node,
    fill = factor(node),
    label = node
  )) +
  geom_sankey(
    flow.alpha = .8,
    node.color = "gray30"
  ) +
  geom_sankey_label(size = 4,
                    color = "white",
                    fill = "gray30") +
  scale_x_discrete(
    labels = c("Sex", 
               "Have you been on a trip in the last month?",
               "Zika")
  ) +
  labs(
    x = NULL,
    title = NULL
  ) +
  theme_sankey(base_size = 18) +
  innovar::scale_fill_innova("npr") +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = .5),
    plot.margin = margin(5, 0, 5, 0)
  )

sankey_zika
```


```{r eval=FALSE}
ggsave("./sankey_seropositive_zika.png",
       sankey_zika,
       height = 7,
       width = 12,
       dpi = 300)
```

### Sankey Malaria

```{r}
relabels_sankey_malaria <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, any_pv_pf_exposure) %>% 
  count(x, node) %>% 
  group_by(x) %>% 
  mutate(
    percentage = scales::percent(
      n / sum(n),
      accuracy = 0.1
    ),
    node2 = paste0(
      node,
      paste0("\n(", percentage, ")")
    )
  ) %>% 
  ungroup() %>% 
  select(-c(n, percentage))
  
sankey_malaria <- ffi_sankey_format %>% 
  make_long(gender, ffi_is_trip_month, any_pv_pf_exposure) %>% 
  left_join(
    relabels_sankey_malaria,
    by = join_by(x, node)
  ) %>% 
  left_join(
    relabels_sankey_malaria,
    by = join_by(next_x == x, 
                 next_node == node)
  ) %>% 
  mutate(node = node2.x,
         next_node = node2.y) %>% 
  select(-c(node2.x, node2.y)) %>% 
  ggplot(aes(
    x = x,
    next_x = next_x,
    node = node,
    next_node = next_node,
    fill = factor(node),
    label = node
  )) +
  geom_sankey(
    flow.alpha = .8,
    node.color = "gray30"
  ) +
  geom_sankey_label(size = 4,
                    color = "white",
                    fill = "gray30") +
  scale_x_discrete(
    labels = c("Sex", 
               "Have you been on a trip in the last month?",
               "Malaria")
  ) +
  labs(
    x = NULL,
    title = NULL
  ) +
  theme_sankey(base_size = 18) +
  innovar::scale_fill_innova("npr") +
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = .5),
    plot.margin = margin(5, 0, 5, 0)
  )

sankey_malaria
```


```{r eval=FALSE}
ggsave("./sankey_seropositive_malaria.png",
       sankey_malaria,
       height = 7,
       width = 12,
       dpi = 300)
```
